# Generated by Django 3.0.4 on 2020-03-23 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200323_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='poffins',
            field=models.IntegerField(),
        ),
    ]
