# Generated by Django 3.0.4 on 2020-03-23 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='poffins',
            field=models.CharField(max_length=255),
        ),
    ]
