# Generated by Django 3.0.4 on 2020-03-24 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200323_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='loginTime',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
