# Generated by Django 3.0.4 on 2020-03-19 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_origin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ptype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pika_type', models.CharField(max_length=100)),
            ],
        ),
    ]
