# Generated by Django 3.0.4 on 2020-03-19 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_ptype'),
    ]

    operations = [
        migrations.AddField(
            model_name='pika',
            name='pika_type',
            field=models.ManyToManyField(to='main_app.Ptype'),
        ),
    ]
