# Generated by Django 3.0.4 on 2020-03-21 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pika',
            old_name='pic_url',
            new_name='pic',
        ),
        migrations.RemoveField(
            model_name='pika',
            name='pika_type',
        ),
        migrations.RemoveField(
            model_name='pika',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='pikas',
            field=models.ManyToManyField(to='main_app.Pika'),
        ),
        migrations.DeleteModel(
            name='Origin',
        ),
        migrations.DeleteModel(
            name='Ptype',
        ),
    ]
