# Generated by Django 3.0.4 on 2020-03-22 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20200321_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ptype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pika_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='pikas',
        ),
        migrations.AddField(
            model_name='profile',
            name='puffins',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='pikachu',
            field=models.ManyToManyField(to='main_app.Ptype'),
        ),
    ]
