# Generated by Django 3.0.4 on 2020-03-22 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20200322_0018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='puffins',
            new_name='poffins',
        ),
    ]
