# Generated by Django 3.0.4 on 2020-03-22 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20200322_2128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='pikachu',
            new_name='pikas',
        ),
    ]
